### ISSUE TITLE
How to install your library??

### ISSUE THREAD

**Issue by adjian** [ERROPiX/ESP32_AnalogWrite#2]
I just download and copy your library to ESP32 arduino library folder. like this : C:\Users\Administrator\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.1\libraries

But I can't find it in Arduino IDE. I really want to use this library. So can you tell me how to install your library? Thank you so much.

**Comment by ERROPiX** [comment]
If you are using the Arduino IDE, please load the downloaded zip file as shown in the following image 
![importlibraryfromzipfile](https://user-images.githubusercontent.com/6576868/53965410-1a0b0c00-40e9-11e9-93da-f068e22b2bd0.png)

If you are using PlatformIO you can install it from the libraries repository https://platformio.org/lib/show/5819/ESP32%20AnalogWrite

**Comment by adjian** [comment]
@ERROPiX I just try your solution. It worked. Thank you for your help and your library.

**Comment by ERROPiX** [comment]
You are welcome, please share it if you like it 👍
