### ISSUE TITLE
Adding to Arduino index

### ISSUE THREAD

**Issue by CornyjK** [ERROPiX/ESP32_AnalogWrite#5]
Have you tried asking Arduino for adding to index? If not, could I ask?

**Comment by CornyjK** [comment]
I see your library is in PlatformIO registry already.

**Comment by ERROPiX** [comment]
I didn't yet asked them, I added it to PlatformIO myself, I forgot to request addition in the Arduino index

**Comment by CornyjK** [comment]
Could I?

**Comment by ERROPiX** [comment]
yes, of course
