### ISSUE TITLE
License

### ISSUE THREAD

**Issue by CornyjK** [ERROPiX/ESP32_AnalogWrite#6]
Which license covers this library? I'd be glad for MIT, because I reused your example for testing with Travis and I'd like it to stay as [example](https://github.com/RoboticsBrno/ArduinoLearningKitStarter-library/blob/CornyjK-analogWriteHAL/examples/ledFade/ledFade.ino) (Our library is licensed under MIT and I would have to write my own library otherwise).

**Comment by ERROPiX** [comment]
I have added MIT license to the repo
